name: DebugRelease train

on:
  # push:
  #   paths:
  #     - .github/workflows/debug_release_train.yml
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: installs
        run: sudo apt-get install musl-tools
      - uses: actions/checkout@v2
        with:
          repository: sourcegraph/sourcegraph
          path: sourcegraph
          ref: v4.1.2
      - uses: actions/setup-node@v2
        with:
          node-version: '^v16.7.0'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
      - name: Apply patches
        run: |
          cd $GITHUB_WORKSPACE/sourcegraph
          git apply ../patches/*
      - name: build server
        env:
          VERSION: dev
          IMAGE: simhnna/sourcegraph
        run: |
          docker login --username "$docker_username" --password "$docker_password"
          cd $GITHUB_WORKSPACE/sourcegraph/cmd/server
          ./pre-build.sh
          ./build.sh
          docker tag "${IMAGE}:latest" "${IMAGE}:${VERSION}"
          docker push ${IMAGE}:${VERSION}
