name: DebugRelease train

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: sourcegraph/sourcegraph
          path: sourcegraph
      - uses: actions/setup-node@v3
        with:
          node-version: '^v16.7.0'
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.16.2'
      - name: build server
        env:
          PUSH_VERSION: dev
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd "$(git rev-parse --show-toplevel)"
          bash train.bash
