name: Release Train

on:
  push:
    paths:
      - .github/workflows/release_train.yml
      - .latest_version
      - train.bash
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: sourcegraph/sourcegraph
          path: sourcegraph
      - uses: actions/setup-node@v2
        with:
          node-version: '^v16.0.7'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
      # - name: Apply patches
      #   run: |
      #     cd $GITHUB_WORKSPACE/sourcegraph
      #     git apply ../patches/auth.patch
      - name: trigger build script
        env:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd "$(git rev-parse --show-toplevel)"
          bash train.bash
